/**
 * Tree-sitter grammar for Lingua Franca
 * AUTO-GENERATED from the official Xtext grammar by xtext2ts.
 *
 * Do not edit this file directly. Instead:
 *   1. Modify xtext2ts/overrides.py for tree-sitter-specific rules
 *   2. Run: python -m xtext2ts --xtext path/to/LinguaFranca.xtext --output tree-sitter-lf/grammar.js
 *
 * @see https://github.com/lf-lang/lingua-franca/blob/master/core/src/main/java/org/lflang/LinguaFranca.xtext
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

// Helper functions
const commaSep = (rule) => optional(commaSep1(rule));
const commaSep1 = (rule) => seq(rule, repeat(seq(',', rule)));

module.exports = grammar({
  name: 'lf',

  externals: ($) => [$._code_body],
  extras: ($) => [/\s/, $.line_comment, $.block_comment],
  word: ($) => $.identifier,
  inline: ($) => [$.reactor_member],
  conflicts: ($) => [
    [$.ipv4_host, $.named_host, $.hostname],
    [$.time, $.number],
  ],

  rules: {
    source_file: ($) =>
      seq(
        $.target_declaration,
        repeat($.import_statement),
        repeat($.preamble),
        repeat1($.reactor)
      ),

    target_declaration: ($) =>
      seq(
        'target',
        field('name', $.target_language),
        optional(field('config', $.key_value_pairs)),
        optional(';')
      ),

    target_language: ($) =>
      choice('C', 'CCpp', 'Cpp', 'Python', 'TypeScript', 'Rust'),

    import_statement: ($) =>
      seq(
        'import',
        field('reactors', commaSep1($.imported_reactor)),
        'from',
        field('source', choice($.string, $.import_path)),
        optional(';')
      ),

    imported_reactor: ($) =>
      seq(
        field('reactor_class', $.identifier),
        optional(seq(
        'as',
        field('name', $.identifier)
      ))
      ),

    import_path: ($) => seq('<', $.path, '>'),

    path: ($) => /[a-zA-Z_.\~\/][a-zA-Z0-9_.\/:~\/-]*/,

    preamble: ($) =>
      seq(
        optional(field('visibility', $.visibility)),
        'preamble',
        field('code', $.code_block)
      ),

    visibility: ($) => choice('private', 'public'),

    reactor: ($) =>
      seq(
        repeat($.attribute),
        optional(choice(seq(optional('federated'), 'main'), 'federated')),
        optional('realtime'),
        'reactor',
        optional(field('name', $.identifier)),
        optional(field('type_params', $.type_parameters)),
        optional(field('parameters', $.parameter_list)),
        optional(seq('at', field('host', $.host))),
        optional(seq('extends', field('extends', commaSep1($.identifier)))),
        field('body', $.reactor_body)
      ),

    type_parameters: ($) => seq('<', commaSep1($.type_parameter), '>'),

    type_parameter: ($) =>
      choice(
        field('literal', $.type_expression),
        field('code', $.code_block)
      ),

    type_expression: ($) =>
      repeat1($.identifier),

    parameter_list: ($) => seq('(', commaSep($.parameter), ')'),

    parameter: ($) =>
      seq(
        repeat($.attribute),
        field('name', $.identifier),
        optional(seq(':', field('type', $.type))),
        optional(field('init', $.initializer))
      ),

    reactor_body: ($) =>
      seq('{', repeat($.reactor_member), '}'),

    reactor_member: ($) =>
      choice(
        $.preamble,
        $.state_var,
        $.method,
        $.input,
        $.output,
        $.timer,
        $.action,
        $.watchdog,
        $.instantiation,
        $.connection,
        $.reaction,
        $.mode
      ),

    state_var: ($) =>
      prec.right(seq(
        repeat($.attribute),
        optional('reset'),
        'state',
        field('name', $.identifier),
        optional(seq(':', field('type', $.type))),
        optional(field('init', $.initializer)),
        optional(';')
      )),

    method: ($) =>
      seq(
        optional(optional('const')),
        'method',
        field('name', $.identifier),
        '(',
        optional(seq(
        field('arguments', $.method_argument),
        repeat(seq(
        ',',
        field('arguments', $.method_argument)
      ))
      )),
        ')',
        optional(seq(
        ':',
        field('return', $.type)
      )),
        field('code', $.code_block),
        optional(';')
      ),

    method_argument: ($) =>
      seq(
        field('name', $.identifier),
        optional(seq(
        ':',
        field('type', $.type)
      ))
      ),

    input: ($) =>
      prec.right(seq(
        repeat($.attribute),
        optional('mutable'),
        'input',
        optional(field('width', $.width_spec)),
        field('name', $.identifier),
        optional(seq(':', field('type', $.type))),
        optional(';')
      )),

    output: ($) =>
      prec.right(seq(
        repeat($.attribute),
        'output',
        optional(field('width', $.width_spec)),
        field('name', $.identifier),
        optional(seq(':', field('type', $.type))),
        optional(';')
      )),

    timer: ($) =>
      prec.right(seq(
        repeat($.attribute),
        'timer',
        field('name', $.identifier),
        optional($.timer_spec),
        optional(';')
      )),

    timer_spec: ($) =>
      seq(
        '(',
        field('offset', $.expression),
        optional(seq(',', field('period', $.expression))),
        ')'
      ),

    action: ($) =>
      prec.right(seq(
        repeat($.attribute),
        optional(field('origin', $.action_origin)),
        'action',
        field('name', $.identifier),
        optional($.action_spec),
        optional(seq(':', field('type', $.type))),
        optional(';')
      )),

    action_origin: ($) => choice('logical', 'physical'),

    action_spec: ($) =>
      seq(
        '(',
        field('min_delay', $.expression),
        optional(
          seq(
            ',',
            field('min_spacing', $.expression),
            optional(seq(',', field('policy', $.string)))
          )
        ),
        ')'
      ),

    watchdog: ($) =>
      seq(
        repeat($.attribute),
        'watchdog',
        field('name', $.identifier),
        '(',
        field('timeout', $.expression),
        ')',
        optional(seq('->', commaSep1($.var_ref_or_mode_transition))),
        field('handler', $.code_block)
      ),

    reaction: ($) =>
      prec.right(seq(
        repeat($.attribute),
        choice('reaction', alias('mutation', $.mutation)),
        optional(field('name', $.identifier)),
        $.trigger_list,
        optional($.source_list),
        optional($.effect_list),
        optional(field('body', $.code_block)),
        optional($.stp),
        optional($.tardy),
        optional($.deadline),
        optional(';')
      )),

    trigger_list: ($) => seq('(', commaSep($.trigger_ref), ')'),

    source_list: ($) => prec.right(commaSep1($.var_ref)),

    effect_list: ($) => seq('->', commaSep1($.var_ref_or_mode_transition)),

    trigger_ref: ($) => choice($.builtin_trigger, $.var_ref),

    builtin_trigger: ($) => choice('startup', 'shutdown', 'reset'),

    var_ref: ($) =>
      prec.left(seq(
        choice(
          seq(
            field('container', $.identifier),
            '.',
            field('variable', $.identifier)
          ),
          field('variable', $.identifier),
          seq(
            'interleaved',
            '(',
            choice(
              seq(
                field('container', $.identifier),
                '.',
                field('variable', $.identifier)
              ),
              field('variable', $.identifier)
            ),
            ')'
          )
        ),
        optional(seq('as', field('alias', $.identifier)))
      )),

    var_ref_or_mode_transition: ($) =>
      choice(
        $.var_ref,
        seq(
        field('transition', $.mode_transition),
        '(',
        field('variable', $.identifier),
        ')'
      )
      ),

    mode_transition: ($) => choice('reset', 'history'),

    stp: ($) =>
      seq(
        choice(
        'STP',
        'STAA'
      ),
        '(',
        field('value', $.expression),
        ')',
        field('code', $.code_block)
      ),

    tardy: ($) => seq('tardy', optional($.code_block)),

    deadline: ($) =>
      seq(
        'deadline',
        '(',
        field('delay', $.expression),
        ')',
        field('code', $.code_block)
      ),

    mode: ($) =>
      seq(
        optional(optional('initial')),
        'mode',
        optional(field('name', $.identifier)),
        '{',
        repeat(choice(
        $.state_var,
        $.timer,
        $.action,
        $.watchdog,
        $.instantiation,
        $.connection,
        $.reaction
      )),
        '}'
      ),

    mode_member: ($) =>
      choice(
        $.state_var,
        $.timer,
        $.action,
        $.watchdog,
        $.instantiation,
        $.connection,
        $.reaction
      ),

    instantiation: ($) =>
      prec.right(seq(
        repeat($.attribute),
        field('name', $.identifier),
        '=',
        'new',
        optional(field('width', $.width_spec)),
        field('class', $.identifier),
        optional(field('type_args', $.type_arguments)),
        '(',
        commaSep($.assignment),
        ')',
        optional(seq('at', $.host)),
        optional(';')
      )),

    type_arguments: ($) => seq('<', commaSep1($.type), '>'),

    assignment: ($) =>
      seq(
        field('lhs', $.identifier),
        field('rhs', $.initializer)
      ),

    connection: ($) =>
      prec.right(seq(
        repeat($.attribute),
        field('left', $.connection_left),
        field('arrow', choice('->', '~>')),
        field('right', commaSep1($.var_ref)),
        optional(seq('after', field('delay', $.expression))),
        optional($.serializer),
        optional(';')
      )),

    connection_left: ($) =>
      choice(
        prec(1, seq('(', commaSep1($.var_ref), ')', optional('+'))),
        commaSep1($.var_ref)
      ),

    serializer: ($) =>
      seq(
        'serializer',
        field('type', $.string)
      ),

    attribute: ($) =>
      prec.right(seq(
        '@',
        field('name', $.identifier),
        optional(seq(
        '(',
        optional(seq(
        $.attribute_parameter,
        repeat(seq(
        ',',
        $.attribute_parameter
      )),
        optional(',')
      )),
        ')'
      ))
      )),

    attribute_parameter: ($) =>
      seq(
        optional(seq(
        field('name', $.identifier),
        '='
      )),
        choice(
        field('value', $.literal),
        field('time', $.time)
      )
      ),

    key_value_pairs: ($) =>
      seq(
        '{',
        optional(seq(
        field('pairs', $.key_value_pair),
        repeat(seq(
        ',',
        field('pairs', $.key_value_pair)
      )),
        optional(',')
      )),
        '}'
      ),

    key_value_pair: ($) =>
      seq(
        field('name', choice(
        $.kebab,
        $.string
      )),
        ':',
        field('value', $.element)
      ),

    kebab: ($) =>
      seq(
        choice(
        $.identifier,
        'physical'
      ),
        repeat(seq(
        '-',
        $.identifier
      ))
      ),

    element: ($) =>
      choice(
        field('keyvalue', $.key_value_pairs),
        field('array', $.array),
        field('literal', $.literal),
        field('time', $.time),
        field('id', $.path)
      ),

    array: ($) =>
      seq(
        '[',
        field('elements', $.element),
        repeat(seq(
        ',',
        field('elements', $.element)
      )),
        optional(','),
        ']'
      ),

    type: ($) =>
      choice(
        'time',
        seq(
          $.dotted_name,
          optional($.type_arguments),
          repeat('*'),
          optional($.c_style_array_spec)
        ),
        $.code_block
      ),

    dotted_name: ($) =>
      prec.left(seq(
        $.identifier,
        repeat(seq(
        choice(
        '.',
        '::'
      ),
        $.identifier
      ))
      )),

    c_style_array_spec: ($) => seq('[', choice(']', seq($.integer, ']'))),

    width_spec: ($) =>
      seq(
        '[',
        choice(
          ']',
          seq($.width_body, ']')
        )
      ),

    width_body: ($) => seq($.width_term, repeat(seq('+', $.width_term))),

    width_term: ($) =>
      choice(
        field('width', $.integer),
        field('parameter', $.identifier),
        seq(
        'widthof(',
        field('port', $.var_ref),
        ')'
      ),
        field('code', $.code_block)
      ),

    initializer: ($) =>
      choice(
        seq('=', $.expression),
        $.braced_list_expression,
        $.parenthesis_list_expression
      ),

    expression: ($) =>
      choice(
        $.time,
        $.literal,
        $.identifier,
        $.code_block,
        $.braced_list_expression,
        $.bracket_list_expression,
        $.parenthesis_list_expression
      ),

    braced_list_expression: ($) => prec(-1, seq('{', commaSep($.expression), '}')),

    bracket_list_expression: ($) =>
      seq(
        '[',
        optional(seq(
        field('items', $.expression),
        repeat(seq(
        ',',
        field('items', $.expression)
      ))
      )),
        optional(','),
        ']'
      ),

    parenthesis_list_expression: ($) =>
      seq(
        '(',
        optional(seq(
        field('items', $.expression),
        repeat(seq(
        ',',
        field('items', $.expression)
      ))
      )),
        optional(','),
        ')'
      ),

    time: ($) =>
      choice(
        seq(field('interval', $.integer), field('unit', $.time_unit)),
        'forever',
        'never'
      ),

    time_unit: ($) => $.identifier,

    host: ($) =>
      choice(
        $.ipv4_host,
        $.ipv6_host,
        $.named_host
      ),

    ipv4_host: ($) =>
      seq(
        optional(seq(
        field('user', $.kebab),
        '@'
      )),
        field('addr', $.ipv4_addr),
        optional(seq(
        ':',
        field('port', $.integer)
      ))
      ),

    ipv6_host: ($) =>
      seq(
        '[',
        optional(seq(
        field('user', $.kebab),
        '@'
      )),
        field('addr', $.ipv6_addr),
        ']',
        optional(seq(
        ':',
        field('port', $.integer)
      ))
      ),

    named_host: ($) =>
      seq(
        optional(seq(
        field('user', $.kebab),
        '@'
      )),
        field('addr', $.hostname),
        optional(seq(
        ':',
        field('port', $.integer)
      ))
      ),

    hostname: ($) =>
      seq(
        $.kebab,
        repeat(seq(
        '.',
        $.kebab
      ))
      ),

    ipv4_addr: ($) => /\d+\.\d+\.\d+\.\d+/,

    ipv6_addr: ($) => /[0-9a-fA-F:]+/,

    literal: ($) =>
      choice($.string, $.char_literal, $.number, $.boolean),

    string: ($) =>
      choice(
        $.double_quoted_string,
        $.triple_double_quoted_string
      ),

    double_quoted_string: ($) => /"[^"\\]*(?:\\.[^"\\]*)*"/,

    triple_double_quoted_string: ($) => /"""[\s\S]*?"""/,

    char_literal: ($) => /'[^'\\](?:\\.[^'\\])*'/,

    number: ($) => choice($.float, $.integer),

    integer: ($) => /-?\d+/,

    float: ($) => /-?\d*\.\d+([eE][+-]?\d+)?/,

    boolean: ($) => choice('true', 'false', 'True', 'False'),

    code_block: ($) => seq('{=', optional($._code_body), '=}'),

    line_comment: ($) => token(choice(seq('//', /.*/), seq('#', /.*/))),

    block_comment: ($) =>
      token(seq('/*', /[^*]*\*+([^/*][^*]*\*+)*/, '/')),

    identifier: ($) => /[a-zA-Z_][a-zA-Z0-9_]*/,

    ipv6_seg: ($) => /[0-9a-fA-F]+/,

  },
});
