"""
Emitter: assembles the final grammar.js from generated and override rules.
"""

from . import ast
from .naming import xtext_to_ts
from .codegen import gen_full_rule
from .overrides import (
    SKIP_RULES, REPLACE_RULES, EXTRA_RULES, GRAMMAR_META, RULE_ORDER,
)

HEADER = """\
/**
 * Tree-sitter grammar for Lingua Franca
 * AUTO-GENERATED from the official Xtext grammar by xtext2ts.
 *
 * Do not edit this file directly. Instead:
 *   1. Modify xtext2ts/overrides.py for tree-sitter-specific rules
 *   2. Run: python -m xtext2ts --xtext path/to/LinguaFranca.xtext --output tree-sitter-lf/grammar.js
 *
 * @see https://github.com/lf-lang/lingua-franca/blob/master/core/src/main/java/org/lflang/LinguaFranca.xtext
 */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

// Helper functions
const commaSep = (rule) => optional(commaSep1(rule));
const commaSep1 = (rule) => seq(rule, repeat(seq(',', rule)));
"""


def emit(grammar: ast.GrammarFile) -> str:
    """Generate a complete grammar.js string."""
    rules = _collect_rules(grammar)
    return _format_grammar(rules)


def _collect_rules(grammar: ast.GrammarFile) -> dict[str, str]:
    """Collect all rules (auto-generated + overrides) keyed by ts name."""
    rules = {}

    # Process Xtext rules
    for rule in grammar.rules:
        if rule.name in SKIP_RULES:
            continue
        if isinstance(rule, ast.TerminalRule):
            continue  # Terminals handled via REPLACE_RULES
        if isinstance(rule, ast.EnumRule):
            ts_name = xtext_to_ts(rule.name)
            if ts_name in REPLACE_RULES:
                rules[ts_name] = REPLACE_RULES[ts_name]
            else:
                rules[ts_name] = _gen_enum_rule(rule)
            continue
        if isinstance(rule, ast.ParserRule):
            ts_name = xtext_to_ts(rule.name)
            if ts_name in REPLACE_RULES:
                rules[ts_name] = REPLACE_RULES[ts_name]
            else:
                body = gen_full_rule(rule.name, rule.body)
                rules[ts_name] = f"($) =>\n      {body}"
            continue

    # Add override replacements not from Xtext
    for name, body in REPLACE_RULES.items():
        if name not in rules:
            rules[name] = body

    # Add extra rules
    for name, body in EXTRA_RULES.items():
        if body is not None and name not in rules:
            rules[name] = body

    return rules


def _gen_enum_rule(rule: ast.EnumRule) -> str:
    """Generate a tree-sitter rule from an Xtext enum."""
    values = []
    for lit in rule.literals:
        if lit.value:
            values.append(f"'{lit.value}'")
    if not values:
        return "($) => choice(/* empty enum */)"
    if len(values) == 1:
        return f"($) => {values[0]}"
    return f"($) => choice({', '.join(values)})"


def _format_grammar(rules: dict[str, str]) -> str:
    """Format the complete grammar.js file."""
    lines = [HEADER]
    lines.append("module.exports = grammar({")
    lines.append("  name: 'lf',")
    lines.append("")

    # Grammar meta
    for key in ("externals", "extras", "word", "inline", "conflicts"):
        if key in GRAMMAR_META:
            lines.append(f"  {key}: {GRAMMAR_META[key]},")
    lines.append("")

    # Rules
    lines.append("  rules: {")

    # Emit rules in specified order first
    emitted = set()
    for name in RULE_ORDER:
        if name in rules:
            lines.append(_format_rule(name, rules[name]))
            emitted.add(name)

    # Emit any remaining rules not in RULE_ORDER
    for name, body in rules.items():
        if name not in emitted:
            lines.append(_format_rule(name, body))

    lines.append("  },")
    lines.append("});")
    lines.append("")

    return "\n".join(lines)


def _format_rule(name: str, body: str) -> str:
    """Format a single rule entry."""
    # Clean up body: remove trailing comma if present
    body = body.rstrip().rstrip(",")
    return f"    {name}: {body},\n"
